[Settings]
  ID = "ac01a129-7415-4955-8a34-dc67b2b94d30"

[build]
  base = "/"
  publish = "dist/"
  functions = "functions"

[build.environment]
  NODE_ENV = "production"
  YARN_VERSION = "1.22.5"
  NODE_VERSION = "14.16.0"

# [context.production.environment]
#   CHAIN_ID = "43114"
#   SUBGRAPH = "mahapo/cryptoneed-avalanche"

# [context.staging.environment]
#   CHAIN_ID = "43114"
#   SUBGRAPH = "mahapo/cryptoneed-avalanche"

# [context.deploy-preview.environment]
#   CHAIN_ID = "4"
#   SUBGRAPH = "mahapo/cryptoneed-testnet"

# [context.branch-deploy.environment]
#   CHAIN_ID = "4"
#   SUBGRAPH = "mahapo/cryptoneed-testnet"

[context.production]
  command = "sh .netlify/scripts/deploy-prod.sh"

[context.deploy-preview]
  command = "sh .netlify/scripts/deploy-dev.sh"

[context.branch-deploy]
  command = "sh .netlify/scripts/deploy-dev.sh"
